version: '3.1'

services:

  web:
    image: chrfr/db_webfrontend:latest

    command: git pull 
    ports:
      - "8097:8000"

    volumes:
      - ./config.js:/home/prognosen/server/config.js
    restart: unless-stopped