version: '3.1'

services:

  web:
    image: chrfr/db_webfrontend:latest

    command: bash -c "git pull && npm install && node /prognosen/server/server.js"
    ports:
      - "8097:8000"

    volumes:
      - ./config.js:/prognosen/server/config.js
    restart: unless-stopped